---
- name: Configure App Server
  hosts: app_servers
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install Packages
      ansible.builtin.apt:
        name:
          - curl
          - docker.io
          - python3-docker
    - name: Copy app
      ansible.builtin.copy:
        src: ../app/
        dest: /home/ansible/app/
        owner: ansible
        group: ansible
        mode: '0755'
    - name: Docker-app
      community.docker.docker_image:
        name: go-app-image
        tag: latest
        source: build
        build:
          path: /home/ansible/app/
    - name: Dosker-start
      community.docker.docker_container:
        name: go-app-container
        image: go-app-image:latest
        state: started
        restart_policy: always
        ports:
          - "8080:8080"

- name: Configure Monitoring Server
  hosts: monitoring_servers
  become: true

  tasks:
    - name: Install Packages
      ansible.builtin.apt:
        name:
          - https://dl.grafana.com/grafana/release/13.2.0/grafana_13.2.0_32077357341_linux_amd64.deb
          - prometheus
    - name: Copy config for prometheus
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        mode: '0644'
    - name: Start Prometheus
      ansible.builtin.systemd:
        name: prometheus
        state: restarted
        enabled: true
    - name: Start Grafana service
      ansible.builtin.systemd:
        name: grafana
        state: started
        enabled: true
